-DARDUINO=180
-I "C:/Archivos de programa/Arduino/hardware/arduino/avr/cores/arduino"
-I "C:/Archivos de programa/Arduino/hardware/arduino/avr/variants/eightanaloginputs"
-I "C:/Archivos de programa/Arduino/hardware/arduino/avr/libraries/EEPROM/src"
-I "C:/Archivos de programa/Arduino/hardware/arduino/avr/libraries/SPI/src"
-I "C:/Archivos de programa/Arduino/hardware/arduino/avr/libraries/Wire/src"

